### ISSUE TITLE
Active skill is missed in console

### ISSUE THREAD

**Issue by acriptis** [deepmipt/dp-agent#9]
The second run was little bit longer:
```
root@78b0394c15ef:/dp-agent# python3 -m core.run
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package perluniprops to /root/nltk_data...
[nltk_data]   Package perluniprops is already up-to-date!
[nltk_data] Downloading package nonbreaking_prefixes to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package nonbreaking_prefixes is already up-to-date!
Provide user id: 2
You (2): кек
Bot:  ничо не разобрать
You (2): скажи шутку
Bot:  .Моя кошка быстреенабирает текст на клавиатуре))) Набирай слово АНЕКДОТ
You (2): анекдот
Bot:  Каждому овощу свой фрукт.
You (2): анекдот
Bot:  Люблю смотреть хорошее, качественное, большое кино!
You (2): что ты умеешь?
Bot:  Я тоже это умею.
You (2): что такое нейронная сеть?
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/dp-agent/core/run.py", line 166, in <module>
    main()
  File "/dp-agent/core/run.py", line 161, in main
    responses = message_processor([message], [1])
  File "/dp-agent/core/run.py", line 142, in infer_cmd
    date_times=date_times, locations=locations, channel_types=['cmd_client'] * len(messages))
  File "/dp-agent/core/agent.py", line 46, in __call__
    sent_responses = self.postprocessor(me_dialogs)
  File "/dp-agent/core/postprocessor.py", line 21, in __call__
    if ner_annotations and (response['active_skill'] == 'chitchat'):
  File "/usr/local/lib/python3.6/dist-packages/mongoengine/base/document.py", line 223, in __getitem__
    raise KeyError(name)
KeyError: 'active_skill'
```

**Comment by my-master** [comment]
Fixed by #18
